import os

# ============================================
# CONFIG: BASE DIRECTORY NAME
# ============================================
BASE_DIR = "Tableau Mastery Roadmap"


# ============================================
# ROADMAP HIERARCHY
# Each key = Chapter folder
# Each value = dict of Section -> list of Subtopic folders
# ============================================

roadmap = {
    "CHAPTER 1 - Tableau Foundations": {
        "1.1 Tableau’s Identity": [
            "The purpose Tableau serves in modern analytics",
            "Tableau as a visual-first computation engine",
            "How Tableau abstracts SQL for analysts",
            "Why Tableau encourages exploratory analysis",
            "The role of Tableau in self-service BI",
            "When Tableau is preferable over Excel",
            "When Tableau is preferable over Power BI",
            "When Tableau is not the right tool",
            "The difference between analysis and reporting in Tableau",
            "Tableau’s evolutionary history",
        ],
        "1.2 Tableau Products Ecosystem": [
            "Tableau Desktop core capabilities",
            "Tableau Cloud role in collaborative analytics",
            "Tableau Server infrastructure logic",
            "Tableau Prep Builder for ETL",
            "Tableau Prep Conductor inside enterprise pipelines",
            "Tableau Public limitations",
            "Tableau Mobile design considerations",
            "Reader vs Server consumers",
            "Viewer, Explorer, Creator license patterns",
            "How licenses impact dashboard design",
        ],
        "1.3 File Structures": [
            "TWB XML logic",
            "TWBX storage behavior",
            "Extract file structure (Hyper internals at a high level)",
            "TDS data source metadata",
            "TDSX packaged metadata",
            "Bookmark usage patterns",
            "Tableau logs directory types",
            "Backgrounder logs vs desktop logs",
            "Query logs vs extract logs",
            "Workbook dependency chains",
            "Embedded vs published data source architecture",
            "Workbook portability issues",
            "Data source version mismatches",
            "Workbook version compatibility rules",
            "Extract dependency tracking",
        ],
        "1.4 Interface Fluency": [
            "Full data pane structure",
            "Field categories inside data pane",
            "Hiding vs grouping fields",
            "Using custom folders",
            "Custom sorting of fields",
            "Dynamic search within data pane",
            "Show Me logic",
            "Marks card as a grammar of graphics",
            "Dual-axis indicators in the interface",
            "Pane vs Header differences",
            "Multi-axis pane splitting",
            "Tooltip editing layout",
            "Status bar rendering logic",
            "Worksheet tab management",
            "Workbook navigation habits",
        ],
        "1.5 Workspace Customization": [
            "Saving default field formats",
            "Default number formats",
            "Default color palettes for fields",
            "Custom palette installation",
            "Setting preferred font families",
            "Turning off auto-updates for performance",
            "Pane-only updates",
            "Changing calc editor font size",
            "Custom keyboard shortcuts",
            "Custom view bookmarks",
            "Compatible and incompatible features by version",
            "Managing saved data sources",
            "Saving custom start pages",
            "Window layout persistence",
            "Toolbar customization",
            "Installing extensions",
            "Setting up debugging modes",
            "Using Performance Recorder from interface",
            "Exporting performance recordings",
            "Using the Data Source tab efficiently",
        ],
        "1.6 Conceptual Thinking": [
            "Tableau’s order of operations",
            "Pill behaviors and what they imply",
            "Data modeling mental framework",
            "Visual encoding fundamentals",
            "Thinking in marks rather than rows",
            "Grain identification",
            "Why Tableau hates ambiguity",
            "How Tableau decides aggregation",
            "Mental model for fields vs views",
            "Tableau as a semantic translator",
        ],
    },

    "CHAPTER 2 - Data Connections & Modeling": {
        "2.1 Connecting to Files": [
            "Excel engine limitations",
            "Long text truncation issues",
            "Data interpreter behaviors",
            "Header detection logic",
            "Leading and trailing spaces in Excel",
            "Unioning sheets automatically",
            "Handling named ranges",
            "Refreshing Excel data",
            "Multi-sheet schema mismatches",
            "CSV delimiter detection",
            "Encoding problems in CSV",
            "Working with TSV",
            "Fixed-width file handling",
            "PDF import pitfalls",
            "Extract caching for local files",
        ],
        "2.2 Connecting to Databases": [
            "Server-side authentication models",
            "Initial SQL usage",
            "Session parameter management",
            "Temp table creation in some connections",
            "Live connection query pushing",
            "Materialized views in databases",
            "Query folding concepts",
            "Extract vs live in relational databases",
            "Schema discovery",
            "Case sensitivity issues",
            "Stored procedure restrictions",
            "Custom SQL performance implications",
            "Parameterized Custom SQL",
            "Multiple connection handling",
            "Connection pooling behavior",
            "Publishing with embedded credentials",
            "OAuth token refresh issues",
            "Service accounts in Tableau",
            "Cross-database join performance",
            "SSL connections",
        ],
        "2.3 Cloud Integrations": [
            "Google Analytics sampling issues",
            "Salesforce API limits",
            "OData constraints",
            "BigQuery billing considerations",
            "Snowflake warehouse impact",
            "Pre-authentication required for cloud sources",
            "Token expiry patterns",
            "Tableau Bridge architecture",
            "Bridge pooling",
            "Bridge scheduling strategies",
            "Bridge live query tunneling",
            "Cloud connectors and unsupported data types",
            "Extracting from rate-limited APIs",
            "Pagination in Web Data Connectors",
        ],
        "2.4 Data Roles": [
            "Why blue pills filter rows",
            "Why green pills affect axes",
            "Continuous-time data behavior",
            "Discrete date truncation",
            "Custom date hierarchies",
            "Geographic role overrides",
            "Non-standard geographic fields",
            "Mapping FIPS codes",
            "Null geographic roles",
            "Role propagation after joins",
        ],
        "2.5 Metadata Modeling": [
            "Splitting fields intelligently",
            "Automatic vs custom split usage",
            "Pivoting for wide tables",
            "De-pivoting multi-header Excel sheets",
            "Data reshaping for time series",
            "Field renaming conventions",
            "Metadata grid for column cleanup",
            "Aliasing fields",
            "Default aggregation patterns",
            "Dataset profiling inside Tableau",
            "Validating row counts",
            "Checking field uniqueness",
            "Comparing schema drift",
            "Rebuilding broken data pane links",
            "Detecting over-nested dimensions",
            "When to hide unused fields",
            "Using describe feature",
            "Detecting rolled-up data",
            "Replacing data source functionality",
            "Data source audit checklist",
        ],
    },

    "CHAPTER 3 - Physical Layer and Logical Layer Modeling": {
        "3.1 Tableau Relationships": [
            "Logical table architecture",
            "Relationship vs join difference",
            "Performance benefits of relationships",
            "Relationship-generated queries",
            "Cardinality settings",
            "Referencing integrity meaning",
            "Selecting correct matching fields",
            "Multiple relationships between tables",
            "Ambiguous relationship handling",
            "Relationship-driven LOD behavior",
            "Why relationships reduce duplication",
            "Why relationships sometimes underperform",
            "Relationship warnings",
            "Identity fields in relationships",
            "Granularity drift in relationships",
            "Relationship with extracts",
            "Relationship-driven aggregation mismatches",
            "Understanding many-to-many performance",
            "Multi-fact modeling",
            "Conformed vs non-conformed dimensions",
        ],
        "3.2 Physical Joins": [
            "Join culling",
            "Join order rules",
            "Join precedence",
            "Join condition testing",
            "Preventing Cartesian joins",
            "Join duplicates detection",
            "Null behavior in joins",
            "Join type selection logic",
            "Complex join calculations",
            "Cross-database join pushdown",
            "Extract-only joins",
            "Multi-join conflict resolution",
            "Join densification",
            "Anti-patterns for joins",
            "Surrogate key creation",
            "Data blending vs joining",
        ],
        "3.3 Unions": [
            "Wide-table unions",
            "Schema alignment",
            "Adding dummy fields for unions",
            "Wildcard union patterns",
            "Multi-folder file unions",
            "Dealing with missing fields in unions",
            "Field typing conflicts",
            "Union performance vs join performance",
            "Using unions for incremental loading",
            "Using unions for row-level slowly changing dimensions",
            "Vertical vs horizontal partitioning",
            "File system organizational structure",
        ],
        "3.4 Grain and Aggregation": [
            "Identifying dataset grain",
            "Mixed-grain dataset issues",
            "Aggregation rules inside Tableau",
            "Why Tableau auto-aggregates",
            "SUM vs ATTR mechanics",
            "ATTR as a safety check",
            "Row-level calculations with mixed grains",
            "Aggregated calculations with mixed grains",
            "Grain conflicts after relationships",
            "Fixing grain mismatches with FIXED LODs",
            "Using densification for missing dates",
            "Data scaffolding construction",
            "Calendar table integration",
            "Time series grain alignment",
            "Period-over-period benchmark grain issues",
            "Multi-grain fact tables",
            "Null grain detection",
            "Surrogate grain assignment",
            "Row uniqueness testing",
            "Stacked fact schemas",
            "Fact table normalization",
            "Combining fact tables with relationships",
            "Preaggregation strategies",
            "Atomic-level storage",
            "Pre-joined marts",
            "De-duplicating via FIXED checks",
            "Confirming grain stability",
            "Transactional vs snapshot fact patterns",
            "Multi-snapshot modeling",
            "Aggregated extract generation",
            "Data blending when grain mismatch persists",
            "When to abandon a data source entirely",
        ],
    },

    "CHAPTER 4 - Calculation Theory": {
        "4.1 Calculation Syntax and Logic": [
            "Syntax parsing rules",
            "Calc editor hints",
            "Auto-complete limitations",
            "Error resolution strategies",
            "Evaluating calculation performance",
            "Commenting conventions",
            "Container functions",
            "Multi-line formatting",
            "Boolean logic as filtering",
            "Nested logical expressions",
            "Safe division patterns",
            "Handling non-numeric results",
            "Integer division pitfalls",
            "Division by zero prevention",
            "Null handling patterns",
            "Using ZN properly",
            "Using IIF vs IF",
            "Using CASE appropriately",
            "CASE type constraints",
            "Multi-condition chaining",
        ],
        "4.2 String Calculations": [
            "Trimming whitespace",
            "Comparing string lengths",
            "Complex string slicing",
            "Regex extraction",
            "Regex replacement",
            "Regex match process",
            "Splitting composite keys",
            "Building composite keys",
            "Normalizing text fields",
            "Cleaning bad identifiers",
            "Domain checking in strings",
            "Detecting inconsistent casing",
            "Removing special characters",
            "Hashing text patterns",
            "Fuzzy-matching concepts",
        ],
        "4.3 Numerical Calculations": [
            "Rounding patterns",
            "Absolute values",
            "Logarithms in Tableau",
            "Power functions",
            "Ranking tie-breaking techniques",
            "Percent-of-total behavior",
            "Weighted averages",
            "Z-scores",
            "Normalization patterns",
            "Scaling values",
            "Bucketing methods",
            "Binning edge cases",
            "Manual bin calculations",
            "Threshold logic",
        ],
        "4.4 Date Calculations": [
            "Anchored date calculations",
            "Fiscal calendar modeling",
            "Custom fiscal year starts",
            "Intelligent date shifting",
            "Working-day logic",
            "Holiday-aware date calculations",
            "Period comparison templates",
            "Rolling windows",
            "Rolling weeks",
            "Rolling months",
            "Rolling quarters",
            "Date granularity truncation",
            "Time difference in hours",
            "Time difference in seconds",
            "Timezone conversion",
            "Current date macros",
            "Parametrized date windows",
            "ISO week conversions",
            "Semi-monthly logic",
            "Last-day-of-month logic",
        ],
        "4.5 Table Calculations": [
            "Table calculation shelf editing",
            "Partition and addressing",
            "Restart clauses",
            "Directional scanning logic",
            "LOOKUP-based offsets",
            "Multi-level addressing",
            "Window-based smoothing",
            "Confidence interval via table calculations",
            "Multi-row transformations",
            "Running aggregates",
            "Difference-from calculations",
            "Percent difference",
            "Ranking transformations",
            "Nested table calculations",
            "Irregular partitions",
            "Table calculation debugging",
            "Table calculation caching",
            "Pane vs table vs cell scope",
            "Mark-level table calculation behaviors",
            "Table calculation performance drains",
            "Table calculation conflicts with filters",
        ],
    },

    "CHAPTER 5 - Level of Detail Expressions": {
        "5.1 LOD Foundations": [
            "LOD purpose",
            "FIXED mechanics",
            "INCLUDE mechanics",
            "EXCLUDE mechanics",
            "LOD calculation timing",
            "How LODs bypass row-level grain",
            "LOD and blending",
            "LOD and table calculations",
            "LOD and filters",
            "LOD within relationships",
        ],
        "5.2 FIXED LOD Patterns": [
            "FIXED for distinct counts",
            "FIXED for KPI computation",
            "FIXED for normalization",
            "FIXED for allocation ratios",
            "FIXED for segmentation",
            "FIXED for baseline snapshots",
            "FIXED for multi-fact models",
            "FIXED with conditional statements",
            "FIXED on high-cardinality fields",
            "FIXED for row deduplication",
        ],
        "5.3 INCLUDE LOD Patterns": [
            "INCLUDE for granular scoring",
            "INCLUDE for cross-row comparisons",
            "INCLUDE for distribution analysis",
            "INCLUDE with dimensions vs measures",
            "INCLUDE for user-level metrics",
            "INCLUDE for stacking calculations",
            "INCLUDE vs nested table calculations",
        ],
        "5.4 EXCLUDE LOD Patterns": [
            "Removing grain for aggregated KPIs",
            "EXCLUDE for smoothing",
            "EXCLUDE vs window average",
            "Hierarchical EXCLUDE usage",
            "EXCLUDE during drilldowns",
            "Avoiding over-aggregation from EXCLUDE",
        ],
        "5.5 Nested LOD Constructions": [
            "Stacking FIXED inside INCLUDE",
            "Stacking EXCLUDE inside FIXED",
            "Multilevel FIXED for multi-segment analytics",
            "LOD nesting performance",
            "Debugging nested LODs",
            "Materializing nested calculations via extract",
            "LOD as surrogate measures",
            "Multi-fact consolidation with nested FIXED",
            "Conditional LODs based on parameters",
            "LODs for user-scoped analytics",
            "LODs feeding table calculations",
            "Using LODs to flatten messy schemas",
            "Detecting flawed LOD assumptions",
            "Choosing LOD vs join preaggregation",
            "Avoiding circular LOD logic",
            "Precomputing LODs outside Tableau",
            "Documenting LODs in projects",
            "Validating LOD correctness",
            "LOD regression testing",
            "LOD collision with context filters",
            "LOD performance triage",
            "When to use aggregated extracts instead of LOD",
            "Building reusable LOD templates",
            "Using parameterized LOD switching",
            "Building LOD decision frameworks",
            "Preventing accidental grain shifts",
            "LOD-driven forecasting prep",
            "LOD-based cohort analysis",
            "LOD for ratio stability",
            "LODs in multi-year historical reporting",
            "Industry-specific LOD usage",
            "Regional vs national FIXED hierarchies",
            "FIXED for sales forecasts",
            "INCLUDE for churn scoring",
            "EXCLUDE for supply chain smoothing",
            "LOD documentation standards",
            "LOD anti-pattern detection",
        ],
    },

    "CHAPTER 6 - Charts, Visual Encodings and Graphical Literacy": {
        "6.1 Standard Chart Fundamentals": [
            "Bar chart encoding",
            "Line chart smoothing",
            "Combo charts",
            "Area charts distortions",
            "Histogram bin density",
            "Tree map pitfalls",
            "Scatter plot jittering",
            "Highlight tables",
            "Density plots",
            "Cumulative distribution visuals",
        ],
        "6.2 Advanced Charting": [
            "Nested bar charts",
            "Clustered bar charts",
            "Slope charts",
            "Dumbbell charts",
            "Spine charts",
            "Marimekko charts",
            "Horizon graphs",
            "Sankey charts via densification",
            "Chord diagrams",
            "Radial bar charts",
            "Radial histograms",
            "Heatmap construction",
            "Waffle charts advanced",
            "Waterfall charts balancing logic",
            "Bullet chart benchmarks",
            "KPI tiles",
            "Sparkline patterns",
            "Trellis charts",
            "Small multiples theory",
            "Progressive disclosure charts",
        ],
        "6.3 Geo-Spatial Visualization": [
            "Symbol map improvements",
            "Filled map smoothing",
            "Dual-map overlays",
            "Multi-layer geospatial stack",
            "Spatial join construction",
            "Distance heatmaps",
            "Contour mapping",
            "Directional arrows",
            "Path maps",
            "Origin-destination flows",
            "Route visualizations",
            "Territory partition visualization",
            "Custom geocoding overrides",
            "Multi-country boundary merging",
            "Climate-band mapping",
            "Grid-based spatial layouts",
            "Using high-resolution shapefiles",
            "Geospatial extract optimization",
            "Complex polygon behavior",
            "Avoiding multi-GB spatial files",
        ],
        "6.4 Visual Design Theory": [
            "Color theory for analytics",
            "Contrast ratios",
            "Sequential palettes",
            "Diverging palettes",
            "Categorical palette clustering",
            "Accessibility color rules",
            "Misleading color gradients",
            "Typography legibility",
            "Spatial grouping by layout",
            "Pre-attentive attributes",
            "Visual hierarchy creation",
            "Grouping through alignment",
            "Visual rhythm",
            "Reducing chartjunk",
            "Understanding ink-to-data ratio",
            "Reducing perceptual overload",
            "Storytelling placement",
            "Annotation strategy",
            "White space as structure",
        ],
        "6.5 Marks and Encoding Deep Cuts": [
            "Mark types",
            "Mark stacking",
            "Mark layering",
            "Mark density effects",
            "Tooltip mark enhancements",
            "Encoding via shape",
            "Encoding via size",
            "Encoding via opacity",
            "Encoding via angle",
            "Encoding via motion using pages",
            "Encoding via position",
        ],
        "6.6 Chart Anti-Patterns": [
            "Pie charts with too many slices",
            "Overuse of 3D visuals",
            "Unsorted bar charts",
            "Poorly chosen baselines",
            "Misaligned axes",
            "Overlapping marks",
            "Ambiguous color meaning",
            "Too many filters",
            "Uncontrolled user interactivity",
            "Excessive chart density",
            "Too many KPIs on one canvas",
            "Data distortion via smoothing",
            "Fake precision in charts",
            "Visual noise from shadows",
            "Unlabeled axes",
            "Floating legends causing confusion",
            "Tooltip overload",
            "Misleading dual-axis scaling",
            "Poorly chosen geographic levels",
            "Overuse of table calculations in visuals",
            "Overuse of tiny multiples",
            "Over-aggregated metrics hiding insights",
            "Bad KPI formatting",
            "Inconsistent color theming",
            "Layout disorganization",
            "Misleading title framing",
            "Legend redundancy",
            "Chart clutter from lines, shapes, and labels",
            "Excessive dashboard text",
            "Non-responsive design mistakes",
            "Unbalanced whitespace",
            "Unnecessary action triggers",
            "User confusion from too many overlays",
            "Using visual metaphor incorrectly",
            "Using color without data meaning",
            "Overuse of icons",
            "Unclear storytelling",
            "Random sort orders",
            "Default formatting left untouched",
            "Gratuitous animation usage",
        ],
    },

    "CHAPTER 7 - Dashboards, Interactions and UX": {
        "7.1 Dashboard Construction": [
            "Tiled vs floating design philosophies",
            "Nested container mechanics",
            "Designing layout grids",
            "Visual spacing frameworks",
            "Using templates for consistency",
            "Multi-dashboard navigation",
            "Building mockups before dashboards",
            "Reducing scroll dependencies",
            "Device-specific dashboards",
            "Dashboard scaling strategies",
            "Optimizing for projector viewing",
            "Optimizing for mobile",
            "Layering sheets for blending effects",
            "Tooltip configurability",
            "Consistent header design",
            "Interactive legends",
            "Using dashboards as menus",
            "Navigation buttons",
            "Hidden navigation areas",
            "Story point sequencing",
        ],
        "7.2 Interactivity Patterns": [
            "Filter actions",
            "Highlight actions",
            "URL actions",
            "Parameter actions",
            "Set actions",
            "Drill-down actions",
            "Drill-up actions",
            "Dynamic sheet swapping",
            "Dynamic field selection",
            "Dynamic metric switching",
            "Parameter-driven chart type switching",
            "Controlling user paths",
            "Custom UI controls using parameters",
            "Hidden filter panels",
            "Multi-level drill hierarchies",
            "Breadcrumb trails",
            "Hover-based interactions",
            "Hover-only detail reveal",
            "Tooltip-based filters",
            "Select-to-highlight interactions",
            "Cascading filters",
            "Avoiding filter conflicts",
            "Performance-sensitive filters",
            "Filter domain management",
            "Using sets as interactive groups",
            "Context filters for heavy datasets",
            "Exclude filters vs hide filters",
            "Multi-dashboard interactions",
            "Global filters across dashboards",
            "Custom query actions",
        ],
        "7.3 UX Patterns": [
            "Designing for executives",
            "Designing for analysts",
            "Designing for field teams",
            "Designing for finance",
            "Designing for supply chain",
            "Designing for sales",
            "Designing for healthcare",
            "Designing for ecommerce",
            "Reducing cognitive load",
            "Reducing user choice paralysis",
            "Designing intuitive flows",
            "Building dashboards like apps",
            "Designing onboarding guides",
            "Anticipating user confusion",
            "Hiding unnecessary controls",
            "Making dashboards self-explanatory",
            "Designing for color-blind users",
            "Using tooltips as documentation",
            "Creating narrative dashboards",
            "Using micro-charts",
            "Embedded glossary panels",
            "Error-state visual design",
            "Consistent KPI representation",
            "Standardized dashboards for teams",
            "Using whitespace to structure thought",
            "Designing dashboards for speed",
            "Designing dashboards for clarity",
            "Designing dashboards for exploration",
            "When to remove interactivity",
            "When to increase interactivity",
        ],
        "7.4 Storytelling": [
            "Structuring a data story",
            "Identifying narrative arcs",
            "Choosing entry points",
            "Designing intentional reveals",
            "Using annotations minimally",
            "Building narrative builds",
            "Building paced disclosures",
            "Maintaining user focus",
            "Ending dashboards with conclusions",
            "Creating dashboard voice",
        ],
    },

    "CHAPTER 8 - Tableau Prep and Data Cleaning": {
        "8.1 Prep Builder Foundations": [
            "Flow structure",
            "Input cleansing",
            "Pivot steps",
            "Aggregate steps",
            "Join steps",
            "Union steps",
            "Cleaning step profiling",
            "Field splitting in Prep",
            "Multi-level pivoting",
            "Flow outputs",
            "Publishing Prep flows",
            "Flow scheduling",
            "Flow documentation",
            "Flow performance optimization",
            "Flow error diagnosis",
        ],
        "8.2 Data Shaping": [
            "Resolving multi-header data",
            "Resolving nested structured data",
            "Cleaning JSON fields",
            "Normalizing text",
            "Removing duplicates",
            "Splitting hierarchical strings",
            "Deduplication strategies",
            "Time-series restructuring",
            "Rolling snapshots",
            "Unpivoting large files",
            "Flattening crosstabs",
            "Repairing mismatched schemas",
        ],
        "8.3 Prep Logic": [
            "Conditional logic inside Prep",
            "Multi-branch flows",
            "Reusable flow components",
            "Parameterizing flows",
            "Environment-specific outputs",
            "Error handling sections",
            "Edge-case validation",
            "Automated outlier removal",
            "Prep for forecasting",
            "Prep for LOD simplification",
            "Prep for custom granularity",
            "Prep for clustering inputs",
            "Prep for spatial files",
        ],
        "8.4 Prep Conductor": [
            "Flow scheduling on server",
            "Execution logs",
            "Flow monitoring",
            "Handling failed flows",
            "Governance rules for flows",
            "Resource allocation",
            "Execution queue logic",
            "Bridge and Prep combined architecture",
            "Optimizing server load",
            "Centralized vs distributed flow management",
        ],
        "8.5 Extract Strategy": [
            "Extract refresh patterns",
            "Extract partitioning",
            "Incremental extract keys",
            "Extract schema drift handling",
            "Extract row-limits and behaviors",
            "Extract compression behavior",
            "Extract failures debugging",
            "Hyper fragment cleanup",
            "Designing extract pipelines",
            "Building extract governance documents",
        ],
    },

    "CHAPTER 9 - Performance Engineering": {
        "9.1 Performance Recorder": [
            "Query timeline interpretation",
            "Rendering time detection",
            "Data source bottleneck analysis",
            "Extract bottleneck analysis",
            "Slow workbook diagnosis",
            "Evidence-based optimization",
            "Saving and comparing recordings",
            "Detecting problematic calculations",
            "Detecting expensive joins",
            "Detecting expensive filters",
        ],
        "9.2 Query Optimization": [
            "Reducing custom SQL usage",
            "Parameter substitution efficiency",
            "Avoiding nested LODs",
            "Avoiding heavy table calculations",
            "Choosing extract vs live strategically",
            "Pre-aggregating data at source",
            "Using database views",
            "Using materialized views",
            "Handling massive fact tables",
            "Caching behaviors",
            "Multi-query dashboards",
            "Parallel query execution limits",
            "Delaying non-critical sheets",
            "Reducing mark count",
            "Reducing tooltip load",
            "Rendering dense geospatial files",
            "Memory pressure handling",
            "Avoiding massive calculated joins",
            "Fixing runaway queries",
            "Workbook load-order design",
            "Using filters that push down to SQL",
            "Avoiding high-cardinality quick filters",
            "Extracting only needed columns",
            "Designing performance budgets",
            "Creating performance SLAs",
        ],
    },

    "CHAPTER 10 - Server, Cloud and Administration": {
        "10.1 Publishing": [
            "Publishing workbook best practices",
            "Publishing data sources best practices",
            "Differences between replace and overwrite",
            "Version management",
            "Publishing strategy for large organizations",
            "Folder structures",
            "Project-level permissions",
            "Workbook ownership logic",
            "Migration between sites",
            "Promoting dashboards across environments",
        ],
        "10.2 Server Administration": [
            "Site roles",
            "Permissions matrix",
            "Content governance",
            "Ownership transfer",
            "Certified data sources workflow",
            "Tableau Catalog usage",
            "Data lineage mapping",
            "Impact analysis",
            "Server health monitoring",
            "Backgrounder load balancing",
            "Extract refresh scheduling",
            "Refresh failures triage",
            "Managing concurrency limits",
            "Group-based access control",
            "Alerting configuration",
            "Subscriptions automation",
            "Server event logs",
            "Admin views",
            "Resource monitoring tool usage",
            "Failure prevention through design",
            "Troubleshooting slow dashboards",
            "Securing sensitive data",
            "Managing external assets",
            "Decommissioning workbooks",
            "Audit and compliance requirements",
        ],
    },

    "CHAPTER 11 - Automation, APIs and Extensions": {
        "11.1 Automation, APIs and Extensions": [
            "Tableau JavaScript API fundamentals",
            "Automating user interactions via JavaScript",
            "Extract API usage",
            "Metadata API usage",
            "Embedding dashboards in web applications",
        ],
    },

    "CHAPTER 12 - Domain Patterns, Testing and Governance": {
        "12.1 Domain Patterns, Testing and Governance": [
            "Finance dashboard design patterns",
            "Healthcare analytics designs",
            "E-commerce funnel dashboards",
            "Data quality testing frameworks",
            "Dashboard governance models",
        ],
    },
}


# ============================================
# HELPER: CREATE FOLDER AND README
# ============================================

def make_folder_with_readme(path, title):
    os.makedirs(path, exist_ok=True)
    readme_path = os.path.join(path, "README.md")
    content_lines = [
        f"# {title}",
        "",
        f"This folder corresponds to: {title}",
        "",
        "Generated as part of the Tableau Mastery Roadmap structure.",
    ]
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write("\n".join(content_lines))


# ============================================
# MAIN: BUILD DIRECTORY TREE
# ============================================

def build_tableau_roadmap(base_dir, structure):
    # Create base directory
    make_folder_with_readme(base_dir, "Tableau Mastery Roadmap Root")

    for chapter, sections in structure.items():
        chapter_path = os.path.join(base_dir, chapter)
        make_folder_with_readme(chapter_path, chapter)

        for section, topics in sections.items():
            section_path = os.path.join(chapter_path, section)
            make_folder_with_readme(section_path, section)

            for topic in topics:
                topic_path = os.path.join(section_path, topic)
                make_folder_with_readme(topic_path, topic)


if __name__ == "__main__":
    build_tableau_roadmap(BASE_DIR, roadmap)
    print("Tableau Mastery Roadmap folder structure successfully created.")
